project_id = "gztjiknpddlkcxuavoeg"

[functions.generate-workout]
verify_jwt = true

[functions.generate-nutrition]
verify_jwt = true

[functions.analyze-meal-photo]
verify_jwt = true

[functions.generate-workout-motivation]
verify_jwt = true

[functions.analyze-diet-file]
verify_jwt = true

[functions.update-daily-recipes]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
