project_id = "gztjiknpddlkcxuavoeg"

[functions.generate-workout]
verify_jwt = true

[functions.generate-nutrition]
verify_jwt = true

[functions.analyze-meal-photo]
verify_jwt = true

[functions.generate-workout-motivation]
verify_jwt = true
